apiVersion: config.songbird-fw.com/v1alpha1
kind: Rule
metadata:
  name: wan-to-nginx # primary key
  uuid: 9768487d-d86b-4d65-aeed-1274f68abc5d
  comment: 'this is a rule'
spec:
  interfaces:
    incoming: wan
    outgoing: lan1
  addresses:
    source: any
    destination: nginx_192.168.0.20
  services:
    - name: web
  nat:
    enabled: true
    type: DNAT
    ip: extip_78.25.11.42
  action: accept
  enabled: true