apiVersion: config.songbird-fw.com/v1alpha1
kind: Color
metadata:
  name: black # primary key
  comment: 'this is a color'
spec:
  hex: 000000
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Color
metadata:
  name: green # primary key
  comment: 'this is a color'
spec:
  hex: 49F527