apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: LAN # primary key
  uuid: e2587a31-79e8-4e79-b61a-c41b42ecbf96
  comment: 'this is a subnet address'
  color: black
spec:
  subnet:
    interface: lan1
    ip: 192.168.0.0
    netmask: 255.255.255.0
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: Printers # primary key
  uuid: e5c14420-df44-404b-a93d-a12f4b953fe1
  comment: 'this is an address'
  color: black
spec:
  range:
    interface: lan2
    start: 192.168.2.1
    end: 192.168.2.10
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: Google # primary key
  uuid: ebc7c88a-2d13-4551-84cb-097b8f901341
  comment: 'this is an address'
  color: black
spec:
  fqdn:
    interface: any
    domainName: www.google.com
    
