apiVersion: config.songbird-fw.com/v1alpha1
kind: AddressGroup
metadata:
  name: grp-lan # primary key
  uuid: c6fd7988-6fdd-40bb-bfbd-2552edad2cca
  comment: 'this is an address group'
  color: green
spec:
  # IDEA: selector with annotation?
  # selector:
  #   config.songbird-fw.com/Name: Web
  addresses:
    - name: LAN
    - name: Printers
