apiVersion: config.songbird-fw.com/v1alpha1
kind: Color
metadata:
  name: black # primary key
  uuid: 584ad891-2f92-4e69-95e1-4f8b81ad1f2b
  comment: 'this is a color'
spec:
  hex: 000000
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Color
metadata:
  name: green # primary key
  uuid: 555e1711-0f45-4ae4-b68b-65fc3f76d69b
  comment: 'this is a color'
spec:
  hex: 49F527