apiVersion: config.songbird-fw.com/v1alpha1
kind: RuleOrder
metadata:
  name: rule-order-wan # primary key
  uuid: 99c376c8-a591-4676-8414-ed8e1ab0b839
  comment: 'this is a rule order'
spec:
  interfaces:
    incoming: wan
    outgoing: lan1
  order:
    - wan-to-nginx