apiVersion: config.songbird-fw.com/v1alpha1
kind: Service
metadata:
  name: dns # primary key
  uuid: 72fc84ba-7589-432a-95b3-16a40107577b
  comment: 'this is a service'
  color: black
  category: 'undefined'
spec:
  protocols:
    - type: TCP
      port: 53
    - type: UDP
      port: 53
