apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: LAN # primary key
  uuid: e2587a31-79e8-4e79-b61a-c41b42ecbf96
  comment: 'this is a subnet address'
  color: black
spec:
  interface: lan1
  subnet:
    ip: 192.168.0.0
    netmask: 255.255.255.0
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: Printers # primary key
  uuid: e5c14420-df44-404b-a93d-a12f4b953fe1
  comment: 'this is an address'
  color: black
spec:
  interface: lan2
  range:
    start: 192.168.2.1
    end: 192.168.2.10
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: Google # primary key
  uuid: ebc7c88a-2d13-4551-84cb-097b8f901341
  comment: 'this is an address'
  color: black
spec:
  interface: any
  fqdn: www.google.com
---
apiVersion: config.songbird-fw.com/v1alpha1
kind: Address
metadata:
  name: win-pc # primary key
  uuid: 4c3ad178-ab82-40e7-9307-8e22afa5b313
  comment: 'this is a mac address'
  color: black
spec:
  interface: any
  mac: 34-29-8F-74-F4-6A
