apiVersion: config.songbird-fw.com/v1alpha1
kind: Rule
metadata:
  name: lan-to-google
  uuid: d42ffd4d-6e92-4403-aa9e-2201b302f288 # primary key
  comment: 'this is a rule'
spec:
  interfaces:
    incoming: lan1
    outgoing: wan
  addresses:
    source: LAN
    destination: Google
  services:
    - name: web
    - name: dns
  action: accept
  enabled: true