apiVersion: config.songbird-fw.com/v1alpha1
kind: RuleOrder
metadata:
  name: rule-order-test # primary key
  uuid: d6a6430e-2207-4c90-91aa-5208f1765bc1
  comment: 'this is a rule order'
spec:
  interfaces:
    incoming: lan1
    outgoing: wan
  order:
    - lan-to-google
    - rule-group-web
